=== PalacinkaVelika/PRI-xampp-/cv5/html/xml/student.dtd
<!ELEMENT student (osobni_udaje, fakulta, rok, predmety)>
<!ELEMENT osobni_udaje (jmeno, prijmeni, studentske_cislo)>
<!ELEMENT jmeno (#PCDATA)>
<!ELEMENT prijmeni (#PCDATA)>
<!ELEMENT studentske_cislo (#PCDATA)>
<!ELEMENT fakulta (#PCDATA)>
<!ELEMENT rok (#PCDATA)>
<!ELEMENT predmety (predmet+)>
<!ELEMENT predmet (#PCDATA)>
<!ATTLIST predmet kod CDATA #REQUIRED>

=== PalacinkaVelika/PRI-xampp-/cv2/student.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE student SYSTEM "student.dtd">
<student>
    <osobni_udaje>
        <jmeno>John</jmeno>
        <prijmeni>Doe</prijmeni>
        <studentske_cislo>123456</studentske_cislo>
    </osobni_udaje>
    <fakulta>Informatika</fakulta>
    <rok>3</rok>
    <predmety>
        <predmet kod="CS101">Úvod do Informatiky</predmet>
        <predmet kod="MATH202">Lineární Algebra</predmet>
        <predmet kod="ENG101">Anglická Kompozice</predmet>
    </predmety>
</student>
